"""add_filename_filepath_ref_submission_id_drop_content


Revision ID: 25b5b34a4c29
Revises: 88bd0854483c
Create Date: 2026-04-16 14:58:13.834073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '25b5b34a4c29'
down_revision: Union[str, Sequence[str], None] = '88bd0854483c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plagiarism_results', sa.Column('reference_submission_id', sa.Uuid(), nullable=True))
    op.alter_column('plagiarism_results', 'reference_filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'plagiarism_results', 'submissions', ['reference_submission_id'], ['id'])
    op.add_column('submissions', sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('submissions', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('submissions', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('submissions', 'file_path')
    op.drop_column('submissions', 'original_filename')
    op.drop_constraint(None, 'plagiarism_results', type_='foreignkey')
    op.alter_column('plagiarism_results', 'reference_filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('plagiarism_results', 'reference_submission_id')
    # ### end Alembic commands ###
